sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
before_install:
  - docker build -t datsteves/image-optimizer-core .
scripts:
  - docker run -d datsteves/image-optimizer-core
install: true